# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResultWindowV2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont
from PyQt5.QtMultimedia import QMediaPlayer
from PyQt5.QtWidgets import QStyle, QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, ResultWindowV2):
        self.mediaPlayer = QMediaPlayer(None, QMediaPlayer.VideoSurface)
        ResultWindowV2.setObjectName("MainWindow")
        ResultWindowV2.resize(1092, 866)
        self.centralwidget = QtWidgets.QWidget(ResultWindowV2)
        self.centralwidget.setObjectName("centralwidget")
        # 新增
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QVideoWidget(self.groupBox)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 11)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        # self.spinBox.setGeometry(QtCore.QRect(130, 30, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.gridLayout.addWidget(self.comboBox, 0, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        # 设置按钮风格
        self.pushButton.setIcon(self.style().standardIcon(QStyle.SP_MediaPlay))
        self.horizontalLayout.addWidget(self.pushButton)

        # 进度条
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setRange(0, 0)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 11)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 5, 1, 1)
        self.gridLayout.setRowStretch(1, 2)
        ResultWindowV2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ResultWindowV2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1038, 23))
        self.menubar.setObjectName("menubar")
        ResultWindowV2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ResultWindowV2)
        self.statusbar.setObjectName("statusbar")
        # self.statusBar.setFont(QFont("Noto Sans", 7))
        # self.statusBar.setFixedHeight(14)
        ResultWindowV2.setStatusBar(self.statusbar)

        self.retranslateUi(ResultWindowV2)
        QtCore.QMetaObject.connectSlotsByName(ResultWindowV2)

        # 界面关闭事件，询问用户是否关闭
    def closeEvent(self, event):
        reply = QMessageBox.question(self, '退出', "是否要退出该界面？",
                                        QMessageBox.Yes | QMessageBox.No, QMessageBox.No)
        if reply == QMessageBox.Yes:
            # 清除视频查询结果
            # self.widget.rem
            # self.widget.clearFocus()
            event.accept()
        else:
            event.ignore()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "查询检测视频"))
        self.label.setText(_translate("MainWindow", "查询第"))
        self.label_4.setText(_translate("MainWindow", "的检测过程"))
        self.comboBox.setItemText(0, _translate("MainWindow", "左手"))
        self.comboBox.setItemText(1, _translate("MainWindow", "右手"))
        self.comboBox.setItemText(2, _translate("MainWindow", "手机盒_1"))
        self.comboBox.setItemText(3, _translate("MainWindow", "手机盒_2"))
        self.comboBox.setItemText(4, _translate("MainWindow", "手机盒_3"))
        self.comboBox.setItemText(5, _translate("MainWindow", "手机盒_4"))
        self.comboBox.setItemText(6, _translate("MainWindow", "手机盒_5"))
        self.comboBox.setItemText(7, _translate("MainWindow", "手机盒_6"))
        self.comboBox.setItemText(8, _translate("MainWindow", "手机盒_7"))
        self.comboBox.setItemText(9, _translate("MainWindow", "手机盒_8"))
        self.comboBox.setItemText(10, _translate("MainWindow", "手机盒_9"))
        self.comboBox.setItemText(11, _translate("MainWindow", "手机盒_10"))
        self.comboBox.setItemText(12, _translate("MainWindow", "纸带"))
        self.comboBox.setItemText(13, _translate("MainWindow", "标签"))
        self.comboBox.setItemText(14, _translate("MainWindow", "胶带封装"))
        self.label_3.setText(_translate("MainWindow", "个中箱检测流程中"))
        self.pushButton.setText(_translate("MainWindow", ""))
        self.pushButton_2.setText(_translate("MainWindow", "查询"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
